app:
  connection:
    threadCount: 3
  sports-to-parse: Football,Tennis,Ice Hockey,Basketball
  events-to-parse: 2
  base-url: https://leonbets.com

logging:
  level:
    root: INFO
    com.dp_ua: INFO
  file:
    name: ./logs/file.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
